apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordd-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordd
                port:
                  number: 2345
