apiVersion: v1
kind: Service
metadata:
  name: wordd
spec:
  type: {{ .Values.service.type }}
  selector:
    app: wordd
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
