apiVersion: v1
kind: Service
metadata:
  name: wordd
  namespace: {{ .Values.global.namespace }}
  labels:
    app: wordd
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 2345
  selector:
    app: wordd
