apiVersion: v1
kind: Service
metadata:
  name: dictd
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: dictd  # Make sure this matches the Deployment labels
  ports:
    - protocol: TCP
      port: 2628
      targetPort: 2628
