FROM golang:1.24-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o tilemasters ./cmd/tilemasters

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/tilemasters .
EXPOSE 3883
CMD ["./tilemasters"]
